-- MySQL Script generated by MySQL Workbench
-- Thu Jun 10 19:36:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------
-- Пользователи

-- -----------------------------------------------------
-- Schema users
--
-- Пользователи
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users` DEFAULT CHARACTER SET utf8 ;
USE `users` ;

-- -----------------------------------------------------
-- Table `users`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`users` (
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `dt_add` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`profiles` (
  `address` VARCHAR(45) NULL,
  `bd` DATETIME NULL,
  `adout` VARCHAR(45) NULL,
  `phone` INT NULL,
  `skype` VARCHAR(20) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`tasks` (
  `dt_add` DATETIME NULL,
  `category_id` VARCHAR(10) NULL,
  `description` VARCHAR(45) NULL,
  `expire` DATETIME NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `budget` INT NULL,
  `lat` INT NULL,
  `long` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`categories` (
  `category` VARCHAR(10) NULL,
  `icon` BLOB NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`cities` (
  `city` VARCHAR(20) NULL,
  `lat` INT NULL,
  `long` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`replies` (
  `dt_add` DATETIME NULL,
  `rate` INT NULL,
  `description` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`opinions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`opinions` (
  `dt_add` DATETIME NULL,
  `rate` INT NULL,
  `descriotion` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
