-- MySQL Script generated by MySQL Workbench
-- Mon Jun 21 16:38:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 1820637-task-force-1
-- -----------------------------------------------------
-- 1820637-task-force-1

-- -----------------------------------------------------
-- Schema 1820637-task-force-1
--
-- 1820637-task-force-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `1820637-task-force-1` DEFAULT CHARACTER SET utf8 ;
USE `1820637-task-force-1` ;

-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATE NOT NULL COMMENT 'Таблица пользователей',
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `e-mail` VARCHAR(40) NOT NULL,
   PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`profiles` (
  `avatar_file` VARCHAR(20) NULL,
  `download_files` VARCHAR(50) NULL,
  `date_of_birth` DATETIME NOT NULL,
  `address` VARCHAR(100) NULL,
  `city_id` INT NOT NULL,
  `about` VARCHAR(200) NOT NULL,
  `e-mail` VARCHAR(40) NOT NULL,
  `phone` INT NULL,
  `skype` VARCHAR(20) NULL,
  `other_conntact` VARCHAR(20) NULL,
  `rating` INT NULL,
  `last-activity` DATETIME NOT NULL,
  `box_hide_contacts` TINYINT(1) NULL,
  `box_hide_profile` TINYINT(1) NOT NULL,
  `box_message` TINYINT(1) NOT NULL,
  `box_actions` TINYINT(1) NOT NULL,
  `box_reply` TINYINT(1) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATE NOT NULL COMMENT 'Таблица заданий',
  `short_description` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `category_id` INT NOT NULL,
  `point` POINT NULL,
  `city_id` INT NULL,
  `files_url` VARCHAR(50) NULL,
  `date_expire` DATE NULL,
  `budget` INT NULL,
  `owner_id` INT NOT NULL,
  `worker_id` INT NULL,
  `task_status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`categories` (
  `category-id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(20) NOT NULL COMMENT 'Таблица категорий',
  `icon_url` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`category-id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(20) NOT NULL COMMENT 'Таблица городов',
  `point` POINT NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`replies` (
  `reply_id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NOT NULL COMMENT 'Таблица откликов на задания',
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `budjet` INT NULL,
  PRIMARY KEY (`reply_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`opinions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`opinions` (
  `opinion_id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATE NOT NULL COMMENT 'Таблица отзывов',
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `rate` INT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`opinion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`chat` (
  `chat_id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL COMMENT 'Таблица чата',
  `receiver_id` INT NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`chat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `1820637-task-force-1`.`user_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1820637-task-force-1`.`user_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `categoryID` INT NOT NULL COMMENT 'Таблица связи пользователей и категорий',
  INDEX `userID` (`userID`),
  INDEX `categoryID` (`categoryID`),
 CONSTRAINT `FK_user` FOREIGN KEY (`userID`) 
        REFERENCES `users` (`users_id`) ON DELETE CASCADE,
    CONSTRAINT `FK_category` FOREIGN KEY (`categoryID`) 
        REFERENCES `categories` (`category_id`) ON DELETE CASCADE,
        PRIMARY KEY (`id`),
        UNIQUE KEY `relation_row_unique` (`ticketID`,`nominationID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
